export const flightStaticText: string[] = [
  "Xem chi tiết",
  "Chi tiết",
  "Hạng vé",
  "Hành lý xách tay",
  "Hành lý ký gửi",
  "Chi tiết hành trình",
  "Hạng:",
  "Chiều đi",
  "Chiều về",
  "Sắp xếp",
  "Đề xuất",
  "Đang tải dữ liệu chuyến bay",
  "Số điểm dừng",
  "điểm dừng",
  "Chuyến bay thẳng",
  "Bay thẳng",
  "Chọn",
  "Hiển thị giá",
  "Giá chưa bao gồm thuế phí",
  "Thời gian khởi hành",
  "Hãng hàng không",
  "Xóa bộ lọc",
  "Khách",
  "Đặt vé",
  "Thay đổi",
  "Tổng",
  "Chưa bao gồm",
  "Không có chuyến bay nào trong ngày hôm nay.",
  "Điều kiện vé",
  "Chi tiết chuyến bay",
  "Quý khách vui lòng chuyển sang ngày khác để đặt vé. Xin cám ơn!",
  "Đang tải thêm chuyến bay",
  "Tổng tiền thanh toán",
  "Thời gian",
  "Giờ cất cánh",
  "Giờ hạ cánh",
  "Đăng ký nhân vé giá rẻ",
  "Đặt vé nhanh tại HappyBook",
  "Hành lý xách tay",
  "Hành lý ký gửi",
  "Hoàn vé",
  "Đổi vé",
  "Được phép",
  "Phí vui lòng liên hệ booker",
];

export const visaStaticText: string[] = [
  "Dịch vụ visa",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Loại Visa",
  "Điểm đến",
  "Thời gian làm Visa",
  "Thời gian lưu trú",
  "Số lần nhập cảnh",
  "Phí nộp tại ĐSQ",
  "Dịch",
  "Xem thêm",
  "Không tìm thấy dữ liệu phù hợp",
];

export const labelRatingStaticText: string[] = [
  "Tệ",
  "Không hài lòng",
  "Bình thường",
  "Hài lòng",
  "Xuất sắc",
  "Hướng dẫn viên",
  "Lộ trình",
  "Phương tiện đưa đón",
  "Giá cả",
  "Đánh giá chung",
];

export const dinhCuStaticText: string[] = [
  "Dịch vụ định cư",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
  "Đang tải dữ liệu",
  "Xem thêm",
];

export const comboStaticText: string[] = [
  "Tìm kiếm",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
  "Đang tải dữ liệu",
  "Xem thêm",
];

export const ProductFilterStaticText: string[] = [
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
];

const visaStaticText2: string[] = [
  "Cẩm nang visa",
  "Dịch vụ Visa nổi bật",
  "Dịch vụ làm visa nhanh chóng, uy tín, hỗ trợ 24/7. Tỷ lệ đậu cao!",
  "Tìm Visa theo địa danh, điểm đến",
  "Tìm theo điểm đến, hoạt động",
  "Theo địa danh, điểm đến",
  "Loại Visa",
  "Chọn loại Visa",
  "Dịch vụ visa",
  "Các bước làm visa tại HappyBook Travel",
  "Làm visa đơn giản và nhanh chóng, với đội ngũ chuyên nghiệp hỗ trợ chuyên nghiệp từ khâu chuẩn bị hồ sơ đến khi nhận visa.",
  "Điền form thông tin đơn giản, nhanh chóng. Thông tin được bảo mật.",
  "Nhân viên sẽ liên hệ với bạn trong vòng 2h làm việc qua zalo/call. Hoặc bạn liên hệ hotline 1900.633.437 - Nhấn phím (2) (zalo/call).",
  "Tư vấn hoàn thiện hồ sơ: nhân viên visa giàu kinh nghiệm của Happy book sẽ đồng hành hướng dẫn, hỗ trợ bạn suốt quá trình chuẩn bị hồ sơ.",
  "Sau khi hồ sơ đã hoàn chỉnh, nhân viên Happy book nộp hồ sơ visa lên Lãnh sự quán các nước.",
  "Sau quá trình đợi LSQ xét duyệt hồ sơ, nhân viên Happybook sẽ thông báo kết quả và chuyển phát hồ sơ cho khách hàng.",
];

const homeStaticText: string[] = [
  "Combo siêu hot hôm nay",
  "Đặt ngay hôm nay, kẻo lỡ cơ hội!",
  "Tour HOT",
  "Trải nghiệm sắc vàng và khám phá văn hóa mùa thu!",
  "Đa dạng lựa chọn khách sạn",
  "Bạn muốn đi đâu chơi?",
  "Cẩm nang du lịch",
  "Đối Tác Hàng Không",
  "Chúng tôi tự hào là đại lý cấp 1 của các hãng hàng không uy tín tại Việt Nam như:",
];

const headerStaticText: string[] = [
  "Trang chủ",
  "Về chúng tôi",
  "Liên Hệ",
  "Tin tức",
  "Tours",
  "Tour nội địa",
  "Tour quốc tế",
  "Vé máy bay",
  "Visa",
  "Du thuyền",
  "Du thuyền Sài Gòn",
  "Du thuyền Hạ Long",
  "Khách sạn",
  "Bảo hiểm",
  "Vé vui chơi",
  "Combo",
  "Khác",
  "Định cư",
  "Đăng ký CTV",
  "Tư vấn visa",
  "Hướng dẫn thanh toán",
  "Hướng dẫn đặt vé",
  "Thông tin chuyển khoản",
  "Điều khoản sử dụng",
  "Chính sách bảo mật",
  "Bắt đầu hành trình với HappyBook",
];

const footerStaticText: string[] = [
  "Hotline vé máy bay:",
  "Nhấn phím (1)",
  "Hotline Visa - hộ chiếu:",
  "Nhấn phím (2)",
  "Hotline Tour du lịch:",
  "Nhấn phím (3)",
  "Email Chính thức:",
  "Email tuyển dụng - đăng ký CTV:",
  "Trụ sở chính:",
  "Tầng 1, Phong Phú Tower, 93/10 Quang Trung, Khu phố 1, Phường Tăng Nhơn Phú, Thành phố Hồ Chí Minh, Việt Nam",
  "Chi nhánh 1:",
  "124 Lê Quang Định, P.Bình Thạnh, TP.HCM",
  "Về HappyBook",
  "Về chúng tôi",
  "Liên hệ chúng tôi",
  "Theo dõi chúng tôi",
  "Dịch vụ",
  "Dịch vụ làm Visa",
  "Hình thức thanh toán",
  "CÔNG TY TNHH TMDV DU LỊCH HAPPYBOOK",
  "Mã số doanh nghiệp: 0314012158 do Sở Kế hoạch & Đầu tư TP HCM cấp ngày 15/09/2016 - Cấp thay đổi ngày 26/03/2024",
];

const generalStaticText: string[] = [
  "Chọn điểm đi",
  "Chọn điểm đến",
  "Từ",
  "Đến",
  "Ngày đi",
  "Ngày về",
  "Số lượng khách",
  "Tìm kiếm",
  "Hành khách",
  "Tổng tiền thanh toán",
  "Xem tất cả",
  "Đăng ký",
  "Tư vấn",
  "Nộp hồ sơ",
  "Đợi kết quả",
  "Điểm đến được yêu thích",
  "Điểm đi",
  "Điểm đến",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp...",
  "Lựa Chọn Không Giới Hạn",
  "Vô vàn hành trình, triệu cảm hứng",
  "Dịch Vụ Cá Nhân Hóa",
  "Chăm sóc đặc biệt, trải nghiệm độc đáo",
  "Giá Trị Vượt Trội",
  "Chất lượng đỉnh, đảm bảo giá tốt nhất",
  "Vì sao nên chọn HappyBook",
  "Đội ngũ Happybook tư vấn",
  "hỗ trợ nhiệt tình 24/7",
  "Sản phẩm đa dạng, ",
  "giá cả tốt nhất",
  "Đơn vị hơn 8 năm kinh nghiệm.",
  "Lấy chữ tín làm đầu",
  "Thông tin đang cập nhật...",
  "Câu hỏi thường gặp",
  "Địa chỉ",
  "Tiếng Anh",
  "Tiếng Việt",
  "Người lớn",
  "Trẻ em",
  "Em bé",
  "tuổi",
  "Chọn ngày",
  "Chat với chúng tôi qua",
  "Xin vui lòng liên hệ HappyBook để biết thêm chi tiết.",
  "Các gói dịch vụ",
  "Chọn các gói dịch vụ",
  "Chi tiết địa điểm",
  "Lưu ý",
  "Giá từ",
  "Xem thêm",
  "Giá",
  "Hành trình",
];
const tourStaticText: string[] = [
  "Tour & Trải nghiệm",
  "Chơi Hè Thả Ga, Không Lo Về Giá",
  "Tour trong nước",
  "Tour Du Lịch Nước Ngoài Cao Cấp",
  "Trải Nghiệm Thế Giới, Khám Phá Bản Thân",
];
const comboStaticText2: string[] = [
  "Khám phá các điểm đến HOT",
  "Các combo du lịch ưu đãi",
  "Tìm Combo du lịch",
];

const contactStaticText: string[] = [
  "Liên hệ với HappyBook",
  "Chúng tôi luôn sẵn sàng lắng nghe và hỗ trợ bạn. Nếu có bất kỳ câu hỏi nào hoặc cần trợ giúp, đừng ngần ngại liên hệ với chúng tôi qua các kênh dưới đây:",
  "Bạn có thể gửi thông tin yêu cầu của mình qua mẫu liên hệ dưới đây, và chúng tôi sẽ phản hồi trong thời gian sớm nhất.",
];

const aboutUsStaticText: string[] = [
  "HappyBook tự hào là đối tác tin cậy",
  "HappyBook luôn đặt chữ TÍN lên hàng đầu. Với sự phát triển không ngừng, chúng tôi đã xây dựng một đội ngũ chuyên viên năng động, giàu kinh nghiệm và luôn tận tâm phục vụ quý khách. Sự hài lòng của khách hàng là kim chỉ nam cho mọi hoạt động của chúng tôi.",
  "10 năm hình thành và phát triển",
  "HappyBook đã khẳng định vị thế của mình là đại lý cấp 1 chuyên cung cấp vé máy bay trong nước và quốc tế. Chúng tôi hiện là đối tác uy tín của nhiều hãng hàng không lớn tại Việt Nam và trên thế giới, mang đến cho khách hàng những lựa chọn đa dạng và phù hợp nhất.",
  "Dịch Vụ “Nổi Bật” Của Chúng Tôi",
  "HappyBook cam kết mang đến cho quý khách hàng những dịch vụ tốt nhất với chi phí hợp lý, bao gồm:",
  "Đại lý vé máy bay",
  "HappyBook là đơn vị chuyên xử lý vé đoàn, vé quốc tế đặc biệt các chặng bay Úc/ Châu Âu/Mỹ/Canada với giá cực kì tốt giảm sâu tới 50%",
  "Hệ thống đặt vé happy book.com.vn cung cấp vé máy bay của tất cả các hãng hàng không nội địa và quốc tế với thao tác đơn giản, hỗ trợ 24/7",
  "Hồ sơ visa",
  "Hỗ trợ tư vấn hồ sơ visa các nước: Ấn Độ - Dubai - Trung Quốc - Nhật - Hàn - Đài - Úc - Châu Âu - Mỹ - Canada,...",
  "Chúng tôi tự hào là đơn vị xử lý hồ sơ Visa khách hàng một cách logic, giúp tỉ lệ đậu cao nhất với chi phí xử lý cực kỳ cạnh tranh",
  "Khách sạn",
  "HappyBook hợp tác ký hợp đồng đại lý với hơn 1000 khách sạn trên toàn quốc, tập trung chủ yếu khách sạn 4 sao 5 sao, khu resort nghỉ dưỡng, Combo Vé máy bay và khách sạn của Happy Book tập trung dòng sản phẩm cao cấp phù hợp với nhóm, gia đình giúp khách hàng có những trải nghiệm hài lòng",
  "Tour du lịch",
  "HappBook cung cấp các tour du lịch quốc tế chất lượng, giá cả cạnh tranh nhất. Các Tour nổi bật: Thái Lan, Trung Quốc, Hàn Quốc, Nhật Bản, Châu Âu, Mỹ,...",
  "Cam Kết Của Chúng Tôi",
  "Tư vấn chuyên nghiệp về các thủ tục và dịch vụ.",
  "Giao vé theo yêu cầu, đảm bảo đúng hạn.",
  "Phương thức thanh toán đơn giản, nhanh chóng và tiện lợi.",
  "Mang đến sự hài lòng tối đa cho khách hàng.",
  "Đội ngũ của chúng tôi",
];

const authStaticText: string[] = [
  "Đăng ký",
  "Bạn đã có tài khoản?",
  "Bạn chưa có tài khoản?",
  "Đăng nhập",
  "Thông tin tài khoản",
  "Lịch sử đặt vé",
  "Đổi mật khẩu",
  "Đăng xuất",
  "Mật khẩu",
  "Nhập lại mật khẩu",
  "Tên tài khoản hoặc địa chỉ email",
];

const formStaticText: string[] = [
  "Tên dịch vụ",
  "Họ và tên",
  "Số điện thoại",
  "Email",
  "Nhập",
  "Hãy chia sẽ nhu cầu của bạn",
  "Gửi",
];

export const unifiedStaticText: string[] = [
  ...homeStaticText,
  ...headerStaticText,
  ...footerStaticText,
  ...generalStaticText,
  ...tourStaticText,
  // === Flight Search Form ===
  "Một chiều",
  "Khứ hồi",
  "Tìm vé rẻ",
  "Những chuyến bay phổ biến",
  "Vé Máy Bay Một Chiều Dành Cho Bạn",
  "Vé Máy Bay Khứ Hồi Dành Cho Bạn",
  "Điểm đến nội địa",
  "Điểm đến quốc tế",
  // === Hotel  ===
  "Thành phố, địa điểm hoặc tên khách sạn:",
  "Khách sạn nổi bật",
  "Khách Sạn Phổ Biến tại Việt Nam",
  "Thành Phố Phổ Biến tại Việt Nam",
  // === Visa  ===
  ...visaStaticText2,
  // === Vé vui chơi  ===
  "Tìm vé vui chơi",
  ...comboStaticText2,
  ...contactStaticText,
  ...formStaticText,
  ...authStaticText,
  ...aboutUsStaticText,
  ...flightStaticText,
];
