export const flightStaticText: string[] = [
  "Xem chi tiết",
  "Chi tiết",
  "Hạng vé",
  "Hành lý xách tay",
  "Hành lý ký gửi",
  "Chi tiết hành trình",
  "Hạng:",
  "Chiều đi",
  "Chiều về",
  "Sắp xếp",
  "Đề xuất",
  "Đang tải dữ liệu chuyến bay",
  "Số điểm dừng",
  "điểm dừng",
  "Chuyến bay thẳng",
  "Bay thẳng",
  "Chọn",
  "Hiển thị giá",
  "Giá chưa bao gồm thuế phí",
  "Thời gian khởi hành",
  "Hãng hàng không",
  "Xóa bộ lọc",
  "Khách",
  "Đặt vé",
  "Thay đổi",
  "Tổng",
  "Chưa bao gồm",
  "Không có chuyến bay nào trong ngày hôm nay.",
  "Điều kiện vé",
  "Chi tiết chuyến bay",
  "Quý khách vui lòng chuyển sang ngày khác để đặt vé. Xin cám ơn!",
  "Tổng tiền thanh toán",
];

export const visaStaticText: string[] = [
  "Dịch vụ visa",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Loại Visa",
  "Điểm đến",
  "Thời gian làm Visa",
  "Thời gian lưu trú",
  "Số lần nhập cảnh",
  "Phí nộp tại ĐSQ",
  "Dịch",
  "Xem thêm",
  "Không tìm thấy dữ liệu phù hợp",
];

export const labelRatingStaticText: string[] = [
  "Tệ",
  "Không hài lòng",
  "Bình thường",
  "Hài lòng",
  "Xuất sắc",
  "Hướng dẫn viên",
  "Lộ trình",
  "Phương tiện đưa đón",
  "Giá cả",
  "Đánh giá chung",
];

export const dinhCuStaticText: string[] = [
  "Dịch vụ định cư",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
  "Đang tải dữ liệu",
  "Xem thêm",
];

export const comboStaticText: string[] = [
  "Tìm kiếm",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
  "Đang tải dữ liệu",
  "Xem thêm",
];

export const ProductFilterStaticText: string[] = [
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
];
