import { translateText } from "@/utils/translateApi";
import { formatTranslationMap } from "@/utils/translateDom";

export const flightStaticText: string[] = [
  "Chuyến đi",
  "Chuyến về",
  "Xem chi tiết",
  "Chi tiết",
  "Thu gọn",
  "Hạng vé",
  "Hành lý xách tay",
  "Hành lý ký gửi",
  "Chi tiết hành trình",
  "Hạng:",
  "Chiều đi",
  "Chiều về",
  "Sắp xếp",
  "Đề xuất",
  "Đang tải dữ liệu chuyến bay",
  "Số điểm dừng",
  "điểm dừng",
  "Chuyến bay thẳng",
  "Bay thẳng",
  "Chọn",
  "Rẻ nhất",
  "Hiển thị giá",
  "Giá chưa bao gồm thuế phí",
  "Thời gian khởi hành",
  "Hãng hàng không",
  "Xóa bộ lọc",
  "Khách",
  "Đặt vé",
  "Thay đổi",
  "Tổng",
  "Chưa bao gồm",
  "Không có chuyến bay nào trong ngày hôm nay.",
  "Điều kiện vé",
  "Chi tiết chuyến bay",
  "Quý khách vui lòng chuyển sang ngày khác để đặt vé. Xin cám ơn!",
  "Đang tải thêm chuyến bay",
  "Tổng tiền thanh toán",
  "Thời gian",
  "Giờ cất cánh",
  "Giờ hạ cánh",
  "Đăng ký nhanh vé giá rẻ",
  "Đặt vé nhanh tại HappyBook",
  "Hành lý xách tay",
  "Hành lý ký gửi",
  "Hoàn vé",
  "Đổi vé",
  "Được phép",
  "Phí vui lòng liên hệ booker",
  "Tóm tắt chuyến bay",
  "Hoàn tất đơn hàng của bạn, để giữ giá tốt nhất",
  "Chuyến bay",
  "Ngày đặt",
  "Khởi hành quá gần (dưới 4h)",
  "Khởi hành < 4h",
  "Cảnh báo giờ bay gần",
  "Chuyến bay này sẽ khởi hành dưới 4 tiếng tính từ hiện tại. Vui lòng đảm bảo bạn kịp thời gian di chuyển ra sân bay và làm thủ tục.",
  "Đồng ý tiếp tục",
];

export const visaStaticText: string[] = [
  "Dịch vụ visa",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Loại Visa",
  "Điểm đến",
  "Thời gian làm Visa",
  "Thời gian lưu trú",
  "Số lần nhập cảnh",
  "Phí nộp tại ĐSQ",
  "Dịch",
  "Xem thêm",
  "Không tìm thấy dữ liệu phù hợp",
  "Giá từ thấp đến cao",
  "Giá từ cao xuống thấp"
];

export const labelRatingStaticText: string[] = [
  "Tệ",
  "Không hài lòng",
  "Bình thường",
  "Hài lòng",
  "Xuất sắc",
  "Hướng dẫn viên",
  "Lộ trình",
  "Phương tiện đưa đón",
  "Giá cả",
  "Đánh giá chung",
];

export const dinhCuStaticText: string[] = [
  "Dịch vụ định cư",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
  "Đang tải dữ liệu",
  "Xem thêm",
  "Giá từ thấp đến cao",
  "Giá từ cao xuống thấp"
];

export const comboStaticText: string[] = [
  "Tìm kiếm",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
  "Đang tải dữ liệu",
  "Xem thêm",
  "Giá từ thấp đến cao",
  "Giá từ cao xuống thấp"
];

export const ProductFilterStaticText: string[] = [
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Không tìm thấy dữ liệu phù hợp",
  "Giá từ thấp đến cao",
  "Giá từ cao xuống thấp",
];

const visaStaticText2: string[] = [
  "Cẩm nang visa",
  "Dịch vụ Visa nổi bật",
  "Dịch vụ làm visa nhanh chóng, uy tín, hỗ trợ 24/7. Tỷ lệ đậu cao!",
  "Tìm Visa theo địa danh, điểm đến",
  "Tìm theo điểm đến, hoạt động",
  "Theo địa danh, điểm đến",
  "Loại Visa",
  "Chọn loại Visa",
  "Dịch vụ visa",
  "Các bước làm visa tại HappyBook Travel",
  "Làm visa đơn giản và nhanh chóng, với đội ngũ chuyên nghiệp hỗ trợ chuyên nghiệp từ khâu chuẩn bị hồ sơ đến khi nhận visa.",
  "Điền form thông tin đơn giản, nhanh chóng. Thông tin được bảo mật.",
  "Nhân viên sẽ liên hệ với bạn trong vòng 2h làm việc qua zalo/call. Hoặc bạn liên hệ hotline 1900.633.437 - Nhấn phím (2) (zalo/call).",
  "Tư vấn hoàn thiện hồ sơ: nhân viên visa giàu kinh nghiệm của Happy book sẽ đồng hành hướng dẫn, hỗ trợ bạn suốt quá trình chuẩn bị hồ sơ.",
  "Sau khi hồ sơ đã hoàn chỉnh, nhân viên Happy book nộp hồ sơ visa lên Lãnh sự quán các nước.",
  "Sau quá trình đợi LSQ xét duyệt hồ sơ, nhân viên Happybook sẽ thông báo kết quả và chuyển phát hồ sơ cho khách hàng.",
];

const homeStaticText: string[] = [
  "Combo siêu hot hôm nay",
  "Đặt ngay hôm nay, kẻo lỡ cơ hội!",
  "Tour HOT",
  "Trải nghiệm sắc vàng và khám phá văn hóa mùa thu!",
  "Đa dạng lựa chọn khách sạn",
  "Bạn muốn đi đâu chơi?",
  "Sim nổi bật",
  "Chọn nhanh các gói eSIM nổi bật cho hành trình Việt Nam và quốc tế",
  "Cẩm nang du lịch",
  "Đối Tác Hàng Không",
  "Chúng tôi tự hào là đại lý cấp 1 của các hãng hàng không uy tín tại Việt Nam như:",
];

const headerStaticText: string[] = [
  "Trang chủ",
  "Về chúng tôi",
  "Liên Hệ",
  "Tin tức",
  "Tours",
  "Tour nội địa",
  "Tour quốc tế",
  "Vé máy bay",
  "Visa",
  "Du thuyền",
  "Du thuyền Sài Gòn",
  "Du thuyền Hạ Long",
  "Khách sạn",
  "Bảo hiểm",
  "Vé vui chơi",
  "Combo",
  "Khác",
  "Định cư",
  "Đăng ký CTV",
  "Tư vấn visa",
  "Danh sách visa các nước",
  "Tư vấn visa miễn phí",
  "Hướng dẫn thanh toán",
  "Hướng dẫn đặt vé",
  "Thông tin chuyển khoản",
  "Điều khoản sử dụng",
  "Chính sách bảo mật",
  "Bắt đầu hành trình với HappyBook",
  "Tiện ích",
  "Dịch vụ tiện ích",
  "Hỗ trợ làm thủ tục nhanh chóng tại sân bay",
  "Bảo vệ sức khỏe và tài sản cho toàn bộ chuyến đi của bạn.",
  "Sim du lịch",
  "Internet toàn cầu với mức giá rẻ hơn data roaming & không cần tháo lắp sim",
  "Tận hưởng không gian thư giãn, cao cấp và tiện nghi trước chuyến hành trình sắp tới.",
  "Sim du lịch Việt Nam",
  "Sim du lịch quốc tế",
  "Kết nối eSIM tiện lợi cho mọi hành trình khám phá Việt Nam.",
  "Phủ sóng đa quốc gia, nhận QR nhanh và online ngay khi hạ cánh.",
  "Flight Radar",
  "Tra cứu và theo dõi tình trạng chuyến bay trực tuyến",
];

const footerStaticText: string[] = [
  "Hotline vé máy bay:",
  "Nhấn phím (1)",
  "Hotline Visa - hộ chiếu:",
  "Nhấn phím (2)",
  "Hotline Tour du lịch:",
  "Nhấn phím (3)",
  "Email Chính thức:",
  "Email tuyển dụng - đăng ký CTV:",
  "Trụ sở chính:",
  "Nội dung",
  "BlueSea Tower, 205B Hoàng Hoa Thám, Phường Bình Lợi Trung, Thành phố Hồ Chí Minh",
  "Tầng 1, Phong Phú Tower, 93/10 Quang Trung, Khu phố 1, Phường Tăng Nhơn Phú, Thành phố Hồ Chí Minh, Việt Nam",
  "Địa điểm kinh doanh:",
  "Về HappyBook",
  "Về chúng tôi",
  "Liên hệ chúng tôi",
  "Theo dõi chúng tôi",
  "Dịch vụ",
  "Dịch vụ làm Visa",
  "Hình thức thanh toán",
  "CÔNG TY TNHH TMDV DU LỊCH HAPPYBOOK",
  "Mã số doanh nghiệp: 0314012158 do Sở Kế hoạch & Đầu tư TP HCM cấp ngày 15/09/2016 - Cấp thay đổi ngày 26/03/2024",
];

const generalStaticText: string[] = [
  "Chọn điểm đi",
  "Chọn điểm đến",
  "Từ",
  "Đến",
  "Ngày đi",
  "Ngày về",
  "Số lượng khách",
  "Tìm kiếm",
  "Hành khách",
  "Tổng tiền thanh toán",
  "Xem tất cả",
  "Đăng ký",
  "Tư vấn",
  "Nộp hồ sơ",
  "Đợi kết quả",
  "Điểm đến được yêu thích",
  "Điểm đi",
  "Điểm đến",
  "Sắp xếp",
  "Mới nhất",
  "Cũ nhất",
  "Giá từ thấp đến cao",
  "Giá từ cao xuống thấp",
  "Không tìm thấy dữ liệu phù hợp...",
  "Lựa Chọn Không Giới Hạn",
  "Vô vàn hành trình, triệu cảm hứng",
  "Dịch Vụ Cá Nhân Hóa",
  "Chăm sóc đặc biệt, trải nghiệm độc đáo",
  "Giá Trị Vượt Trội",
  "Chất lượng đỉnh, đảm bảo giá tốt nhất",
  "Vì sao nên chọn Happybook",
  "Đội ngũ Happybook tư vấn",
  "hỗ trợ nhiệt tình 24/7",
  "Sản phẩm đa dạng, ",
  "giá cả tốt nhất",
  "Đơn vị hơn 8 năm kinh nghiệm.",
  "Lấy chữ tín làm đầu",
  "Thông tin đang cập nhật...",
  "Câu hỏi thường gặp",
  "Địa chỉ",
  "Tiếng Anh",
  "Tiếng Việt",
  "Người lớn",
  "Trẻ em",
  "Em bé",
  "tuổi",
  "Chọn ngày",
  "Chat với chúng tôi qua",
  "Xin vui lòng liên hệ Happybook để biết thêm chi tiết.",
  "Các gói dịch vụ",
  "Chọn các gói dịch vụ",
  "Chi tiết địa điểm",
  "Lưu ý",
  "Giá từ",
  "Xem thêm",
  "Giá",
  "Hành trình",
  "Thông tin liên hệ",
  "Mã khuyến mãi",
  "Chọn mã khuyến mãi...",
  "Không tìm thấy mã khuyến mãi phù hợp",
  "Tổng cộng",
  "Chỉ từ",
  "Thông tin đơn hàng",
  "Tôi muốn xuất hóa đơn",
  "Fast track",
  "Phòng chờ thương gia",
  "Mã đơn hàng",
  "Gói dữ liệu",
  "Khách hàng",
  "Giới tính",
  "Năm sinh",
  "Thông tin hành khách",
  "Dịch vụ mua thêm",
  "Thanh toán sau",
  "Quý khách vui lòng giữ liên lạc để đội ngũ CSKH liên hệ xác nhận",
  "Thanh toán tiền mặt",
  "Thanh toán quét mã QR ngân hàng",
  "Thanh toán Visa, MasterCard, JCB",
  "Chưa chọn phương thức thanh toán",
  "Đã thanh toán",
  "Chi tiết đơn hàng",
  "Trở về trang chủ",
  "Yêu cầu đặc biệt",
  "Tổng giá",
  "Giá giảm",
  "Tổng cộng",
  "Đặt ngay",
  "Số lượng",
  "Loại vé",
  "Phòng",
  "Ngày nhận phòng",
  "Ngày trả phòng",
  "Sản phẩm",
  "Gói",
  "Loại",
  // === Fast Track Booking Detail ===
  "Đang tải thông tin đặt chỗ...",
  "Happybook đã nhận được khoản thanh toán thành công cho đơn hàng",
  "Happybook đã nhận được đơn hàng",
  "Happybook sẽ gửi xác nhận đơn hàng trong thời gian không quá 24h.",
  "Nam",
  "Nữ",
  "Phân loại khách",
  "Cá nhân",
  "Đoàn",
  "Danh sách khách",
  "Khách",
  "Thông tin chuyến bay",
  "Số hiệu chuyến bay",
  "Giờ bay",
  "Giờ đáp",
  "Ngày bay",
  "Vé đã chọn",
  "Vé",
  "Phụ phí đã chọn",
  "Phụ phí",
  "Phụ phí giờ bay thêm",
  "Lưu ý: Phụ phí giờ bay thêm (150.000 VND/vé) sẽ được tính tự động cho các chuyến bay trong khung giờ 23h - 6h sáng",
  "Lưu ý phụ phí giờ bay thêm",
  "Đối với dịch vụ đón sân bay: tính theo giờ hạ cánh",
  "Đối với dịch vụ đón sân bay",
  "Đối với dịch vụ tiễn sân bay: tính theo giờ khởi hành",
  "Đối với dịch vụ tiễn sân bay",
  "Đang tạo link thanh toán...",
  "Đang chờ thanh toán",
  "Thanh toán",
  "Phí xử lý giao dịch thẻ quốc tế (2.5%)",
  "Phí xử lý giao dịch thẻ quốc tế",
  "Không tìm thấy mã đơn hàng",
  "Vui lòng chọn phương thức thanh toán",
  "Không thể tạo link thanh toán. Vui lòng thử lại.",
  "Có lỗi xảy ra khi tạo link thanh toán. Vui lòng thử lại.",
  "Không thể tạo mã QR thanh toán. Vui lòng thử lại.",
  // === Fast Track FormCheckOut ===
  "Tùy chọn",
  "Chọn loại khách để nhập thông tin bổ sung (nếu cần)",
  "Đón/Tiễn cá nhân",
  "Sử dụng thông tin từ form liên hệ",
  "Đón/Tiễn đoàn",
  "Nhập thông tin cho nhiều khách",
  "Đặt lại về mặc định",
  "Danh sách thông tin khách",
  "Số lượng khách tự động khớp với số vé đã chọn",
  "Nhập họ và tên",
  "Nhập số điện thoại",
  "Nhập email",
  "Mở",
  "Vui lòng chọn giới tính",
  "VD: VN123",
  "Vui lòng nhập giờ đáp cho dịch vụ đón sân bay",
  "Vui lòng nhập giờ bay cho dịch vụ tiễn sân bay",
];
const tourStaticText: string[] = [
  "Tour & Trải nghiệm",
  "Chơi Hè Thả Ga, Không Lo Về Giá",
  "Tour trong nước",
  "Tour Du Lịch Nước Ngoài Cao Cấp",
  "Trải Nghiệm Thế Giới, Khám Phá Bản Thân",
];
const comboStaticText2: string[] = [
  "Khám phá các điểm đến HOT",
  "Các combo du lịch ưu đãi",
  "Tìm Combo du lịch",
];

const contactStaticText: string[] = [
  "Liên hệ với HappyBook",
  "Chúng tôi luôn sẵn sàng lắng nghe và hỗ trợ bạn. Nếu có bất kỳ câu hỏi nào hoặc cần trợ giúp, đừng ngần ngại liên hệ với chúng tôi qua các kênh dưới đây:",
  "Bạn có thể gửi thông tin yêu cầu của mình qua mẫu liên hệ dưới đây, và chúng tôi sẽ phản hồi trong thời gian sớm nhất.",
];

const aboutUsStaticText: string[] = [
  "HappyBook tự hào là đối tác tin cậy",
  "HappyBook luôn đặt chữ TÍN lên hàng đầu. Với sự phát triển không ngừng, chúng tôi đã xây dựng một đội ngũ chuyên viên năng động, giàu kinh nghiệm và luôn tận tâm phục vụ quý khách. Sự hài lòng của khách hàng là kim chỉ nam cho mọi hoạt động của chúng tôi.",
  "10 năm hình thành và phát triển",
  "HappyBook đã khẳng định vị thế của mình là đại lý cấp 1 chuyên cung cấp vé máy bay trong nước và quốc tế. Chúng tôi hiện là đối tác uy tín của nhiều hãng hàng không lớn tại Việt Nam và trên thế giới, mang đến cho khách hàng những lựa chọn đa dạng và phù hợp nhất.",
  "Dịch Vụ “Nổi Bật” Của Chúng Tôi",
  "HappyBook cam kết mang đến cho quý khách hàng những dịch vụ tốt nhất với chi phí hợp lý, bao gồm:",
  "Đại lý vé máy bay",
  "HappyBook là đơn vị chuyên xử lý vé đoàn, vé quốc tế đặc biệt các chặng bay Úc/ Châu Âu/Mỹ/Canada với giá cực kì tốt giảm sâu tới 50%",
  "Hệ thống đặt vé happy book.com.vn cung cấp vé máy bay của tất cả các hãng hàng không nội địa và quốc tế với thao tác đơn giản, hỗ trợ 24/7",
  "Hồ sơ visa",
  "Hỗ trợ tư vấn hồ sơ visa các nước: Ấn Độ - Dubai - Trung Quốc - Nhật - Hàn - Đài - Úc - Châu Âu - Mỹ - Canada,...",
  "Chúng tôi tự hào là đơn vị xử lý hồ sơ Visa khách hàng một cách logic, giúp tỉ lệ đậu cao nhất với chi phí xử lý cực kỳ cạnh tranh",
  "Khách sạn",
  "HappyBook hợp tác ký hợp đồng đại lý với hơn 1000 khách sạn trên toàn quốc, tập trung chủ yếu khách sạn 4 sao 5 sao, khu resort nghỉ dưỡng, Combo Vé máy bay và khách sạn của Happy Book tập trung dòng sản phẩm cao cấp phù hợp với nhóm, gia đình giúp khách hàng có những trải nghiệm hài lòng",
  "Tour du lịch",
  "HappBook cung cấp các tour du lịch quốc tế chất lượng, giá cả cạnh tranh nhất. Các Tour nổi bật: Thái Lan, Trung Quốc, Hàn Quốc, Nhật Bản, Châu Âu, Mỹ,...",
  "Cam Kết Của Chúng Tôi",
  "Tư vấn chuyên nghiệp về các thủ tục và dịch vụ.",
  "Giao vé theo yêu cầu, đảm bảo đúng hạn.",
  "Phương thức thanh toán đơn giản, nhanh chóng và tiện lợi.",
  "Mang đến sự hài lòng tối đa cho khách hàng.",
  "Đội ngũ của chúng tôi",
];

const authStaticText: string[] = [
  "Đăng ký",
  "Bạn đã có tài khoản?",
  "Bạn chưa có tài khoản?",
  "Đăng nhập",
  "Thông tin tài khoản",
  "Lịch sử đặt vé máy bay",
  "Lịch sử đặt hàng",
  "Đổi mật khẩu",
  "Đăng xuất",
  "Mật khẩu",
  "Nhập lại mật khẩu",
  "Tên tài khoản hoặc địa chỉ email",
];

const formStaticText: string[] = [
  "Tên dịch vụ",
  "Họ và tên",
  "Số điện thoại",
  "Email",
  "Nhập",
  "Hãy chia sẽ nhu cầu của bạn",
  "Gửi",
];

const simDuLichStaticText: string[] = [
  "Sim du lịch quốc tế eSIM | HappyBook Travel",
  "Mua eSIM du lịch quốc tế giá tốt, nhận QR qua email tức thì. Phủ sóng Nhật Bản, Hàn Quốc, Thái Lan, Trung Quốc, Châu Âu, Mỹ và hơn 30 quốc gia.",
  "Thanh toán eSIM | HappyBook Travel",
  "Điền thông tin và hoàn tất thanh toán mua eSIM du lịch quốc tế.",
  "eSIM du lịch",
  "Đang tải dữ liệu...",
  "Phủ sóng rộng",
  "Giao hàng",
  "Nhận qua email tức thì",
  "Chia sẻ",
  "Hỗ trợ hotspot",
  "Không hỗ trợ hotspot",
  "Kích hoạt",
  "Kích hoạt dễ dàng",
  "Sẵn sàng",
  "Internet sẵn sàng ngay khi hạ cánh",
  "Chọn điểm đến khác",
  "Quốc gia",
  "Cụm quốc gia",
  "Mức giá",
  "Chọn quốc gia...",
  "Không tìm thấy quốc gia",
  "Tìm theo quốc gia, khu vực...",
  "Tìm theo hạn sử dụng, gói data...",
  "Chọn hạn sử dụng, gói data...",
  "Không tìm thấy gói eSIM phù hợp.",
  "Từ",
  "Tổng cộng:",
  "Đã bao gồm thuế và phí xử lý",
  "Đã bao gồm thuế, Miễn phí xử lý",
  "Đặt ngay",
  "Đảm bảo giá tốt nhất",
  "Hỗ trợ khách hàng 24/7",
  "Chi tiết gói dịch vụ",
  "Tóm tắt",
  "Chưa chọn gói",
  "Đơn giá:",
  "Chưa có dữ liệu mức giá.",
  "Đặt lại",
  "Câu hỏi thường gặp (FAQ)",
  "Thiếu thông tin gói eSIM.",
  "Không tìm thấy gói eSIM bạn đã chọn.",
  "Không thể tải chi tiết gói eSIM. Vui lòng thử lại sau.",
  "Không thể tính giá thanh toán lúc này.",
  "Gói eSIM hiện không khả dụng để thanh toán.",
  "Không thể tạo đơn hàng eSIM.",
  "Thiếu thông tin gói eSIM.",
  "Vui lòng nhập email",
  "Email không hợp lệ",
  "Thanh toán eSIM thành công.",
  "Không thể tạo link thanh toán PayPal.",
  "Không thể tạo link thanh toán OnePay.",
  "Đang chuyển tới PayPal.",
  "Đang chuyển tới trang thanh toán OnePay.",
  "Đã tạo mã thanh toán VietQR.",
  "Vui lòng hoàn tất thanh toán trong:",
  "Thông tin khách hàng & Đơn hàng",
  "Email nhận eSIM:",
  "Họ và tên:",
  "Số điện thoại:",
  "Không có",
  "Giao dịch an toàn & bảo mật",
  "Thông tin thanh toán của bạn được mã hóa 256-bit SSL để đảm bảo an toàn tuyệt đối.",
  "Phương thức thanh toán",
  "Thanh toán quét mã QR",
  "Thẻ tín dụng / Ghi nợ quốc tế",
  "Bằng việc nhấn \"Thanh toán ngay\", bạn đồng ý với",
  "Điều khoản dịch vụ",
  "Chính sách bảo mật",
  "của HappyBook.",
  "Quét mã QR để thanh toán",
  "Sau khi chuyển khoản thành công, hệ thống sẽ tự động cập nhật trạng thái đơn hàng.",
  "Đã thanh toán",
  "Chờ thanh toán",
  "Số tài khoản",
  "Chủ tài khoản",
  "Ngân hàng",
  "Nội dung chuyển khoản",
  "Tổng thanh toán:",
  "Tóm tắt đơn hàng",
  "Số lượng:",
  "Tạm tính",
  "Phí dịch vụ",
  "Miễn phí",
  "Phí thanh toán OnePay",
  "Số tiền thanh toán:",
  "Tới bước thanh toán",
  "Gói eSIM này hiện chưa thể thanh toán. Vui lòng chọn gói khác.",
  "Mã đơn hàng:",
  "Mã đơn:",
  "Cần hỗ trợ?",
  "Chat với chúng tôi",
  "Thông tin liên lạc",
  "Vui lòng cung cấp thông tin để chúng tôi gửi mã QR eSIM cho bạn.",
  "Địa chỉ email",
  "Mã kích hoạt eSIM sẽ được gửi qua email này, hãy kiểm tra kỹ nhé.",
  "Sửa thông tin",
  "Thêm Họ tên & Số điện thoại (Tùy chọn)",
  "Thêm thông tin liên lạc",
  "Thông tin liên lạc sẽ được sử dụng trong trường hợp cần hỗ trợ kỹ thuật hoặc xử lý sự cố với eSIM của bạn.",
  "Họ và tên",
  "Số điện thoại",
  "Ví dụ: Nguyen Van A",
  "Ví dụ: 0909 123 456",
  "Lưu thông tin",
  "Huỷ bỏ",
  "Vui lòng nhập họ tên",
  "Vui lòng nhập số điện thoại",
  "Số điện thoại không hợp lệ",
  "Đóng",
  "Chọn gói dịch vụ —",
  "Nhà mạng:",
  "Xác nhận",
  "Không thể tải dữ liệu eSIM. Vui lòng thử lại sau.",
  "Tất cả",
  "Chỉ internet",
  "Có số điện thoại",
  "Không giới hạn",
  "Loại gói",
  "Xem gói khác",
  "Hạn sử dụng (Ngày)",
  "Ngày",
  "Gói Data",
  "Loại dịch vụ",
  "Số lượng",
  "Chưa chọn",
  "Loại dịch vụ:",
  "Hotspot:",
  "Wi-Fi:",
  "Dung lượng:",
  "Tốc độ:",
  "Đã bao gồm thuế và phí xử lý",
  "Đã bao gồm thuế, Miễn phí xử lý",
  "Đảm bảo giá tốt nhất",
  "Hỗ trợ khách hàng 24/7",
  "Đang tải dữ liệu gói eSIM.",
  "eSIM này phù hợp với thiết bị hỗ trợ eSIM, đã mở khóa mạng và có thể quét mã QR từ email sau khi thanh toán.",
  "Chính sách hoàn tiền của eSIM phụ thuộc vào trạng thái mã QR, thời điểm kích hoạt và lỗi từ nhà cung cấp.",
  "Tôi nhận eSIM bằng cách nào?",
  "Sau khi thanh toán, hệ thống sẽ gửi mã QR hoặc hướng dẫn cài đặt qua email đã đăng ký.",
  "Tôi có thể cài eSIM trước khi bay không?",
  "Có. Bạn có thể cài trước, nhưng chỉ nên kích hoạt khi đến đúng quốc gia/khu vực sử dụng để tránh mất thời gian sử dụng của gói.",
  "Nếu đổi thiết bị thì sao?",
  "Nhiều eSIM chỉ cài được một lần. Hãy giữ thiết bị chính và liên hệ hỗ trợ trước khi reset hoặc chuyển máy.",
  "Nếu không tìm thấy gói phù hợp thì sao?",
  "Bạn có thể dùng ô tìm kiếm hoặc lọc theo quốc gia ở phía dưới để đổi sang gói khác trong cùng khu vực.",
  "Khả năng tương thích thiết bị",
  "Chính sách hoàn tiền",
  "Câu hỏi thường gặp (FAQ)",
  "Gói có số điện thoại, phù hợp cho cuộc gọi và SMS tùy theo nhà mạng.",
  "Gói tập trung vào data, phù hợp cho nhu cầu truy cập internet khi du lịch.",
  "Có hỗ trợ chia sẻ kết nối.",
  "Không hỗ trợ chia sẻ kết nối.",
  "Thiết bị vẫn dùng Wi-Fi bình thường khi chuyển sang eSIM.",
  "Nếu bạn cần phát Wi-Fi, hãy kiểm tra kỹ mô tả gói trước khi mua.",
  "Gói không giới hạn theo chính sách nhà mạng, có thể áp dụng fair use.",
  "Dung lượng hiển thị theo SKU:",
  "đang cập nhật",
  "Gói này",
  "đang được tối ưu cho khu vực",
  "Nếu bạn không chắc thiết bị của mình hỗ trợ eSIM, hãy kiểm tra với nhà sản xuất trước khi kích hoạt.",
  "hãy kiểm tra với nhà sản xuất trước khi kích hoạt.",
  "chu kỳ",
  "gói dịch vụ",
  "Chưa quét QR hoặc chưa kích hoạt: có thể được hỗ trợ xử lý đổi gói/hoàn tiền theo điều kiện.",
  "Đã nhận mã QR: vui lòng kiểm tra lại thiết bị, mạng, và cấu hình trước khi yêu cầu hỗ trợ.",
  "Đã kích hoạt: trường hợp hoàn tiền sẽ được xem xét khi có lỗi kỹ thuật xác nhận từ nhà cung cấp.",
  "Nếu gói hiển thị khác với nhu cầu thực tế, nên liên hệ hỗ trợ trước khi cài đặt để tránh phát sinh chi phí không cần thiết.",
  "Gói này thường được kích hoạt theo chu kỳ",
  "Thời điểm kích hoạt sẽ được xác nhận theo mô tả của gói.",
  "Vui lòng đọc kỹ mô tả gói trước khi đặt mua.",
  "Thông tin liên lạc sẽ được sử dụng trong trường hợp cần hỗ trợ kỹ thuật hoặc xử lý sự cố với eSIM của bạn.",
  "Thêm thông tin liên lạc",
  "Lưu thông tin",
  "Quay lại",
  "Đang tải thông tin gói eSIM...",
  "Quay lại chọn gói",
  "Không tìm thấy dữ liệu gói eSIM.",
  "Quay lại nhập thông tin",
  "Thêm Họ tên & Số điện thoại (Tùy chọn)",
  "Vui lòng cung cấp thông tin để chúng tôi gửi mã QR eSIM cho bạn.",
  "Mã kích hoạt eSIM sẽ được gửi qua email này, hãy kiểm tra kỹ nhé.",
  "Sửa thông tin",
  "Thông tin liên lạc",
  "Địa chỉ email",
  "Vui lòng nhập họ tên",
  "Vui lòng nhập số điện thoại",
  "Số điện thoại không hợp lệ",
  "Nhận qua email tức thì",
  "Giao hàng",
  "Chia sẻ",
  "Hỗ trợ hotspot",
  "Không hỗ trợ hotspot",
  "Cam kết",
  "Hoàn tiền đầy đủ",
  "Tổng thanh toán",
  "Không tìm thấy gói eSIM phù hợp.",
  "Từ",
  "Vui lòng hoàn tất thanh toán trong:",
  "Thông tin khách hàng & Đơn hàng",
  "Email nhận eSIM:",
  "Họ và tên:",
  "Số điện thoại:",
  "Giao dịch an toàn & bảo mật",
  "Thẻ tín dụng / Ghi nợ quốc tế",
  "Bằng việc nhấn \"Thanh toán ngay\", bạn đồng ý với",
  "Điều khoản dịch vụ",
  "Chính sách bảo mật",
  "của HappyBook.",
  "Quét mã QR để thanh toán",
  "Sau khi chuyển khoản thành công, hệ thống sẽ tự động cập nhật trạng thái đơn hàng.",
  "Đã thanh toán",
  "Chờ thanh toán",
  "Số tài khoản",
  "Chủ tài khoản",
  "Ngân hàng",
  "Nội dung chuyển khoản",
  "Tạm tính",
  "Phí dịch vụ",
  "Miễn phí",
  "Phí thanh toán OnePay",
  "Số tiền thanh toán:",
  "Đang tạo đơn hàng...",
  "Thanh toán qua PayPal",
  "Tạo lại mã thanh toán",
  "Thanh toán ngay",
  "Tới bước thanh toán",
  "Gói eSIM này hiện chưa thể thanh toán. Vui lòng chọn gói khác.",
  "Mã đơn hàng:",
  "Cần hỗ trợ?",
  "Chat với chúng tôi",
  "Ví dụ: Nguyen Van A",
  "Ví dụ: 0909 123 456",
  "Huỷ bỏ",
  "Bạn đã hủy thanh toán",
  "Bạn có thể quay lại chọn phương thức thanh toán khác.",
  "Quay về eSIM",
  "Một chiều",
  "Khứ hồi",
  "Tìm vé rẻ",
  "Những chuyến bay phổ biến",
  "Vé Máy Bay Một Chiều Dành Cho Bạn",
  "Vé Máy Bay Khứ Hồi Dành Cho Bạn",
  "Điểm đến nội địa",
  "Điểm đến quốc tế",
];

export const unifiedStaticText: string[] = [
  ...homeStaticText,
  ...headerStaticText,
  ...footerStaticText,
  ...generalStaticText,
  ...tourStaticText,
  // === Flight Search Form ===
  "Một chiều",
  "Khứ hồi",
  "Tìm vé rẻ",
  "Những chuyến bay phổ biến",
  "Vé Máy Bay Một Chiều Dành Cho Bạn",
  "Vé Máy Bay Khứ Hồi Dành Cho Bạn",
  "Điểm đến nội địa",
  "Điểm đến quốc tế",
  // === Hotel  ===
  "Thành phố, địa điểm hoặc tên khách sạn:",
  "Khách sạn nổi bật",
  "Khách Sạn Phổ Biến tại Việt Nam",
  "Thành Phố Phổ Biến tại Việt Nam",
  // === Visa  ===
  ...visaStaticText2,
  // === Vé vui chơi  ===
  "Tìm vé vui chơi",
  ...comboStaticText2,
  ...contactStaticText,
  ...formStaticText,
  ...authStaticText,
  ...aboutUsStaticText,
  ...flightStaticText,
  ...simDuLichStaticText,
];

const staticTextTranslationCache = new Map<string, Promise<Record<string, string>>>();

const getStaticTextCacheKey = (lang: string) => `${lang}:${unifiedStaticText.join("\u0001")}`;

export async function getStaticTextTranslationMap(
  lang: string = "vi"
): Promise<Record<string, string>> {
  const cacheKey = getStaticTextCacheKey(lang);

  if (lang === "vi") {
    return formatTranslationMap(unifiedStaticText);
  }

  const cached = staticTextTranslationCache.get(cacheKey);
  if (cached) return cached;

  const pending = (async () => {
    const translated = await translateText(unifiedStaticText, lang);
    return formatTranslationMap(unifiedStaticText, translated);
  })();

  staticTextTranslationCache.set(cacheKey, pending);
  return pending;
}
